services:
  # Combined backend + frontend service
  - type: web
    name: skedlyze
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALENDAR_API_KEY
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://skedlyze.onrender.com
